### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by surfeur5** [Hatry1337/Cubify#2]
hello what is audio format extension?

**Comment by Hatry1337** [comment]
Hi, I usually use mp3s. In most cases it works fine. It can be direct download URL to your track or stream (like icecast, shoutcast and etc.)

**Comment by Hatry1337** [comment]
Also oggs must work

**Comment by surfeur5** [comment]
thank you I use this link me it does not seem to work https://surfruncraft.fr/musique/hide-and-seek.mp3

**Comment by Hatry1337** [comment]
Seems like it must work, I'll check it later

**Comment by surfeur5** [comment]
Thank you for your help

**Comment by Hatry1337** [comment]
> ... https://surfruncraft.fr/musique/hide-and-seek.mp3

You deleted this file? I wanted to test this, but server says that it not found.

**Comment by surfeur5** [comment]
yes I have changed the link http://musique.surfruncraft.fr/hideandseek.mp3 to test san https

**Comment by Hatry1337** [comment]
Interesting, but it works for me. Maybe try to check your open fm radio. Sometimes it lags and don't playing music. Just break it and place again.

**Comment by surfeur5** [comment]
Yes indeed it does it also for some musics which are by default after I am in version 1.7.10 It can perhaps come from that
