### ISSUE TITLE
This program requires an OpenFM radio

### ISSUE THREAD

**Issue by segev1708** [Hatry1337/Cubify#3]
![image](https://user-images.githubusercontent.com/98040924/215549929-f92d4b20-2510-4122-bc5b-04020db4af8a.png)
is it a mod?

**Comment by Hatry1337** [comment]
> ![image](https://user-images.githubusercontent.com/98040924/215549929-f92d4b20-2510-4122-bc5b-04020db4af8a.png)
> 
> is it a mod?

Hello. Yes, OpenFM is OpenComputers addon mod that adds OpenFM Radio block. To make Cubify work you need this mod and you must connect radio block to the computer.

https://www.curseforge.com/minecraft/mc-mods/openfm
