### ISSUE TITLE
what music services can i use and how do i use them

### ISSUE THREAD

**Issue by NixPlayer** [Hatry1337/Cubify#4]
ok, youtube is not supported. Totally fine. But then what service can i use? I tried spotify, but it doesn't work.

**Comment by Hatry1337** [comment]
Hello! This program supports only `.mp3`, `.ogg` audio streams, or direct URLs to files. It is OpenFM audio format restrictions. If you want to play YouTube or other service links you need some API that takes URLs from wanted service and returns direct URL to audio file. I planned to develop something like this, but haven't yet.

**Comment by NixPlayer** [comment]
ok then
