### ISSUE TITLE
servers down and crashes when track lacks duration

### ISSUE THREAD

**Issue by LittleTimmy52** [Hatry1337/Cubify#5]
If I add a track like http://listen.radionomy.com/DeepHouse with no duration because it is a stream and I play it says error nil and highlights require("Screen") over and over, but it does at least set the radio to the music before dieing. Also I cant access cloud tracks because it wont connect presumably your servers are down

**Comment by Hatry1337** [comment]
as a workaround you can put really big value like "999999999999" seconds. 
i'll try to find better solution if i will have hyperfocus on it (can't promise)
also server is up again. thanks for your issue.

**Comment by LittleTimmy52** [comment]
yes I just put the lua 64 bit intager limit and it works just fine it will play for practically ever thanks for the response ill just close the issue since its just a little bug
